name: narwhal_env
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.5.*
  - torchaudio=2.5.*
  - pytorch-cuda=12.1
  - matplotlib
  - ipykernel
  - libsndfile
  - ffmpeg
  - scipy
  - pandas>=1.3
  - numpy>=1.24
  - tqdm
  # remove sox on Windows unless you specifically need CLI sox